#!/usr/bin/env bash

# To run this script enter "./deploy" in your terminal from 
# the root directory without the quotes

git checkout master &&
rm -rf backend/dist &&
cd frontend  &&
npm run build &&
cd .. &&
cp -r frontend/dist backend &&
git add . &&
git commit -m "Updates build for deployment" &&
git subtree push --prefix backend heroku master 
